import { createContext, useContext, useState, useEffect } from "react";
import { hashPassword } from "../utils/crypto";
import api from "../api/axios";

const AuthContext = createContext();

export const useAuth = () => useContext(AuthContext);

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulating checking local storage for persisted session
    try {
      const storedUser = localStorage.getItem("inventory_user");
      if (storedUser) {
        const parsed = JSON.parse(storedUser);
        if (parsed && parsed.id) {
          setUser(parsed);
        } else {
          localStorage.removeItem("inventory_user"); // Corrupt data
        }
      }
    } catch (e) {
      localStorage.removeItem("inventory_user");
      console.error("Auth init error:", e);
    }
    setLoading(false);
  }, []);

  const login = async (username, password) => {
    try {
      const { data } = await api.post('/auth/login', { username, password });
      setUser(data);
      localStorage.setItem("inventory_user", JSON.stringify(data));
      return data;
    } catch (error) {
      console.error("Login failed:", error);
      throw new Error(error.response?.data?.message || "Login xatoligi");
    }
  };

  const loginWithEImzo = async (signature, serial, pinfl) => {
    try {
      // NOTE: We rely on the backend to verify the signature and extract real PINFL.
      // passing 'serial' and 'pinfl' from frontend is just for debugging/fallback if needed,
      // but SECURITY relies on 'signature'.

      const { data } = await api.post('/auth/eimzo', {
        signature,
        // In a strictly secure flow, we should send the original challenge too if it was generated by server
      });

      setUser(data);
      localStorage.setItem("inventory_user", JSON.stringify(data));
      return data;
    } catch (error) {
      console.error("E-IMZO Login failed:", error);
      throw new Error(error.response?.data?.message || "E-Imzo bilan kirishda xatolik");
    }
  };

  const logout = () => {
    if (user) {
      const logs = JSON.parse(localStorage.getItem("inventory_logs") || "[]");
      logs.unshift({
        id: Date.now(),
        action: "Tizimdan chiqdi",
        userName: user.name,
        userRole: user.role,
        timestamp: new Date().toISOString(),
        itemId: null,
        itemName: "Logout"
      });
      localStorage.setItem("inventory_logs", JSON.stringify(logs));
    }
    setUser(null);
    localStorage.removeItem("inventory_user");
  };

  return (
    <AuthContext.Provider value={{ user, login, loginWithEImzo, logout, loading }}>
      {!loading && children}
    </AuthContext.Provider>
  );
};
